//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveBalance
    {
        public int BalanceID { get; set; }
        public int EmployeeID { get; set; }
        public int LeaveTypeID { get; set; }
        public int Year { get; set; }
        public int TotalDays { get; set; }
        public Nullable<int> UsedDays { get; set; }
        public Nullable<int> RemainingDays { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LeaveType LeaveType { get; set; }
    }
}
