//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDocument
    {
        public int DocumentID { get; set; }
        public int TaskID { get; set; }
        public int EmployeeID { get; set; }
        public string DocumentName { get; set; }
        public string FilePath { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Description { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual WorkTask WorkTask { get; set; }
    }
}
