//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskComment
    {
        public int CommentID { get; set; }
        public int TaskID { get; set; }
        public int EmployeeID { get; set; }
        public string CommentText { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsEdited { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual WorkTask WorkTask { get; set; }
    }
}
